routes/web.php
<?php

use App\Http\Controllers\AppointmentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('boilerplate.login');
});

Route::group([
    // 'prefix'     => config('boilerplate.app.prefix', ''),
    'domain' => config('boilerplate.app.domain', ''),
    'middleware' => ['web', 'boilerplate.locale'],
    'as' => 'boilerplate.',
], function () {
    Route::group(['middleware' => ['boilerplate.auth']], function () {
        // patient routes
        Route::group(['middleware' => ['role:patient']], function () {
            Route::post('appointments', [AppointmentController::class, 'store'])->name('appointments.store');
            Route::get('appointments/create', [AppointmentController::class, 'create'])->name('appointments.create');
        });
        // doctor routes
        Route::group(['middleware' => ['role:doctor']], function () {
            Route::put('appointments/{appointment}/update', [AppointmentController::class, 'update'])->name('appointments.update');
        });
         // patient, doctor routes
        Route::group(['middleware' => ['role:patient|doctor']], function () {
            Route::get('appointments', [AppointmentController::class, 'index'])->name('appointments.index');
            Route::get('appointments/{appointment}/edit', [AppointmentController::class, 'edit'])->name('appointments.edit');
        });
        
    });
});

app/Models/Appointment.php
<?php

namespace App\Models;

use App\Models\Boilerplate\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Appointment extends Model
{
    use HasFactory;
    const PENDING_STATUS = 'PENDING';
    const PENDING_COLOR = '#FFD700';
    const CONFIRMED_STATUS = 'CONFIRMED';
    const CONFIRMED_COLOR = '#50C878';
    const REJECTED_STATUS = 'REJECTED';
    const REJECTED_COLOR = '#FF5733';
    const CONFIRMED = 'Yes';
    const NOT_CONFIRMED = 'No';

    protected $guarded = [];

    public function doctor()
    {
        return $this->belongsTo(User::class, 'doctor_id', 'id');
    }
    public function patient()
    {
        return $this->belongsTo(User::class, 'patient_id', 'id');
    }

    public function hour()
    {
        return $this->belongsTo(Hour::class, 'hour_id', 'id');

    }
}

app/Http/Controllers/AppointmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Appointment;
use App\Models\Boilerplate\User;
use App\Models\Hour;
use Illuminate\Support\Facades\DB;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AppointmentController extends Controller
{
    public function index()
    {
        $events = [];

        if (Auth::user()->hasRole('patient')) {
            $appointments = Appointment::where('patient_id', Auth::user()->id)->get();
            foreach ($appointments as $appointment) {
                $dateWithHour = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $appointment->date)
                    ->addHours($appointment->hour->hour)
                    ->format('Y-m-d H:i:s');
                $EndDateWithHour = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $appointment->date)
                    ->addHours($appointment->hour->hour + 1) // + 1 hour
                    ->format('Y-m-d H:i:s');
                $events[] = [
                    'title' => $appointment->doctor->name,
                    'url' => route('boilerplate.appointments.edit', $appointment),
                    'start' =>  $dateWithHour,
                    'end' =>  $EndDateWithHour,
                    'color' => $appointment->color,
                ];
            }
            return view('appointments.patient.list', [
                'events' => $events
            ]);
        } elseif (Auth::user()->hasRole('doctor')) {
            $appointments = Appointment::where('doctor_id', Auth::user()->id)->get();
            foreach ($appointments as $appointment) {
                $dateWithHour = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $appointment->date)
                    ->addHours($appointment->hour->hour)
                    ->format('Y-m-d H:i:s');
                $EndDateWithHour = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $appointment->date)
                    ->addHours($appointment->hour->hour + 1) // + 1 hour
                    ->format('Y-m-d H:i:s');
                $events[] = [
                    'title' => $appointment->patient->name,
                    'url' => route('boilerplate.appointments.edit', $appointment),
                    'start' =>  $dateWithHour,
                    'end' =>  $EndDateWithHour,
                    'color' => $appointment->color,
                    'description' => $appointment->comments,

                ];
            }
            return view('appointments.doctor.list', [
                'events' => $events
            ]);
        }
    }
    public function create()
    {
        $doctors = User::whereRoleIs('doctor')
            ->select(DB::raw("CONCAT(first_name, ' ', last_name) AS full_name"), "id")
            ->pluck("full_name", "id")->toArray();

        $hours = Hour::pluck("hour", "id")->toArray();

        return view('appointments.patient.create', [
            'doctors' => $doctors,
            'hours' => $hours
        ]);
    }

    public function edit(Appointment $appointment)
    {
        if (Auth::user()->hasRole('patient')) {
            return view('appointments.patient.edit', [
                'appointment' => $appointment,
            ]);
        } elseif (Auth::user()->hasRole('doctor')) {
            return view('appointments.doctor.edit', [
                'appointment' => $appointment,
            ]);
        }
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'doctor_select' => [
                'required',
                function ($attribute, $value, $fail) {
                    $doctorExists = User::where('id', $value)->first();
                    if (!$doctorExists || !$doctorExists->hasRole('doctor')) {
                        $fail('The selected doctor does not exist or is not a doctor.');
                    }
                },
            ],
            'date' => 'required|date_format:Y-m-d',
            'hour_select' => [
                'required',
                function ($attribute, $value, $fail) {
                    $hourExists = Hour::where('id', $value)->exists();
                    if (!$hourExists) {
                        $fail('The selected hour does not exist.');
                    }

                    // Check if the selected hour is available for the specified doctor on the given date
                    $doctorId = request('doctor_select');
                    $date = request('date');
                    $isHourAvailable = Appointment::where('doctor_id', $doctorId)
                        ->where('hour_id', $value)
                        ->where('date', $date)
                        ->doesntExist();

                    if (!$isHourAvailable) {
                        $fail('The selected hour is not available for the specified doctor on the given date.');
                    }
                },
            ],
        ]);
        $appointment = Appointment::create([
            'doctor_id' => $request->doctor_select,
            'patient_id' => Auth::user()->id,
            'hour_id' => $request->hour_select,
            'status' => Appointment::PENDING_STATUS,
            'color' => Appointment::PENDING_COLOR,
            'date' => $request->date,
        ]);
        return redirect()->route('boilerplate.appointments.edit', $appointment)
            ->with('growl', [__('appointments.successadd'), 'success']);
    }
    public function update(Appointment $appointment, Request $request)
    {
        if ($appointment->doctor_id != Auth::user()->id) {
            abort(403);
        }

        $this->validate($request, [
            'confirm_select' => 'required|in:Yes,No',
            // 'comments' => '',
        ]);

        if ($appointment->status == Appointment::PENDING_STATUS) {
            if ($request->confirm_select == Appointment::CONFIRMED) {
                $appointment->status = Appointment::CONFIRMED_STATUS;
                $appointment->color = Appointment::CONFIRMED_COLOR;
            } else {
                $appointment->status = Appointment::REJECTED_STATUS;
                $appointment->color = Appointment::REJECTED_COLOR;
            }
            $appointment->save();
        }
        return redirect()->route('boilerplate.appointments.edit', $appointment)
            ->with('growl', [__('appointments.successmod'), 'success']);
    }
}

resources/views/appointments/doctor/edit.blade.php
@extends('boilerplate::layout.index', [
'title' => __('appointments.title'),
'subtitle' => __('appointments.edit.title'),
'breadcrumb' => [
__('appointments.title') => 'boilerplate.appointments.index',
__('appointments.edit.title')
]
])

@section('content')
<form method="POST" action="{{ route('boilerplate.appointments.update', $appointment->id) }}">
    @method('PUT')
    @csrf
    <div class="row">
        <div class="col-12 pb-3">
            <a href="{{ route("boilerplate.appointments.index") }}" class="btn btn-default" data-toggle="tooltip" title="@lang('appointments.returntolist')">
                <span class="far fa-arrow-alt-circle-left text-muted"></span>
            </a>
            @if($appointment->status == \App\Models\Appointment::PENDING_STATUS)
            <span class="btn-group float-right">
                <button type="submit" class="btn btn-primary">
                    @lang('appointments.save')
                </button>
            </span>
            @endif
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @component('boilerplate::card', ['title' => 'appointments.informations'])
            <div class="row">
                <div class="col-lg-10">
                    @component('boilerplate::input', ['name' => 'patient', 'label' => 'appointments.edit.patient_select','value'=> $appointment->patient->name,'readonly'])@endcomponent
                </div>
                <div class="col-lg-2">
                    @component('boilerplate::input', ['name' => 'status', 'label' => 'appointments.status','value'=> $appointment->status,'readonly'])@endcomponent
                </div>
                <div class="col-lg-10">
                    @component('boilerplate::input', ['name' => 'date', 'label' => 'appointments.date','value'=> \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $appointment->date)->format('Y-m-d'),'readonly'])@endcomponent
                </div>
                <div class="col-lg-2">
                    @component('boilerplate::input', ['name' => 'hour', 'label' => 'appointments.edit.hour_select','value'=> $appointment->hour->hour,'readonly'])@endcomponent
                </div>
                @if($appointment->status == \App\Models\Appointment::PENDING_STATUS)
                <div class="col-lg-12">
                    @component('boilerplate::select2', ['name' => 'confirm_select', 'label' => 'appointments.edit.confirm_select'])
                    <option value="Yes">Yes</option>
                    <option value="No">No</option>
                    @endcomponent
                </div>
                @endif
            </div>

            @endcomponent
        </div>
    </div>
</form>
@endsection

resources/views/appointments/doctor/list.blade.php
@extends('boilerplate::layout.index', [
'title' => __('appointments.title'),
'subtitle' => __('appointments.list.title'),
'breadcrumb' => [
__('appointments.list.title') => 'boilerplate.appointments.index'
]
])

@section('content')
@component('boilerplate::card')
<div id='calendar' style="margin-top: 20px;"></div>
@endcomponent
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.12/index.global.min.js'></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var events = <?php echo json_encode($events) ?>;
        var currentDate = new Date();
        var initialDate = currentDate.toISOString().slice(0, 10);

        var calendar = new FullCalendar.Calendar(calendarEl, {
            initialView: 'timeGridWeek',
            initialDate: initialDate,
            headerToolbar: {
                left: 'prev,next',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
            },
            events: events,
            eventContent: function(arg) {
                let html = `<b>${arg.event.title}</b><br/>`;
                if (arg.event.extendedProps.description) {
                    html += `<i>${arg.event.extendedProps.description}</i>`;
                }
                return {
                    html: html
                };
            },
        });

        calendar.render();
    });
</script>
@endsection

@push('css')
<style>
    .img-circle {
        border: 1px solid #CCC
    }

    body {
        font-family: Arial, sans-serif;
        background-color: #f0f0f0;
        margin: 0;
        padding: 0;
    }

    .container {
        max-width: 800px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .input-container {
        display: flex;
        align-items: center;
        margin-bottom: 20px;
    }

    .input-container label {
        margin-right: 10px;
    }

    .input-container select {
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }

    #add-event-btn {
        padding: 8px 16px;
        border: none;
        background-color: #007bff;
        color: white;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

    #add-event-btn:hover {
        background-color: #0056b3;
    }

    .fc-event {
        white-space: normal;
        /* Allows the text to wrap to the next line */
    }
</style>
@endpush